// Projets mis à jour avec toutes les galeries et détails
export const PROJECTS_UPDATED = [
  {
    slug: "3075-boul-mascouche",
    title: "3075 Boul. Mascouche",
    titleEn: "3075 Boul. Mascouche",
    img: "/projets/3075 Boul. Mascouche/IMG_0124.jpg",
    summary: "Aménagement paysager commercial de grande envergure avec multiples phases de développement.",
    summaryEn: "Large-scale commercial landscaping with multiple development phases.",
    description: "Projet commercial majeur incluant l'aménagement de vastes espaces verts, la création de zones de détente et l'intégration de végétation native.",
    descriptionEn: "Major commercial project including the development of vast green spaces, creation of relaxation areas and integration of native vegetation.",
    gallery: [
      "/projets/3075 Boul. Mascouche/IMG_0124.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0125.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0126.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0127.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0128.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0129.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0130.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0131.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0134.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0135.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0136.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0137.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0138.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0139.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0140.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0141.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0483.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0484.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0485.jpg",
      "/projets/3075 Boul. Mascouche/IMG_0486.jpg",
      "/projets/3075 Boul. Mascouche/IMG_3373.jpg",
      "/projets/3075 Boul. Mascouche/IMG_3374.jpg",
      "/projets/3075 Boul. Mascouche/IMG_7057.JPG",
      "/projets/3075 Boul. Mascouche/IMG_7059.JPG",
      "/projets/3075 Boul. Mascouche/IMG_7062.JPG",
      "/projets/3075 Boul. Mascouche/IMG_7072.JPG",
      "/projets/3075 Boul. Mascouche/IMG_8041.JPG"
    ],
    details: {
      budget: "Sur mesure",
      budgetEn: "Custom",
      duration: "10-12 semaines",
      durationEn: "10-12 weeks",
      materials: ["Végétation commerciale", "Pavé uni", "Éclairage paysager", "Système d'irrigation"],
      materialsEn: ["Commercial vegetation", "Interlocking pavers", "Landscape lighting", "Irrigation system"],
      location: "Boul. Mascouche, Mascouche",
      locationEn: "Boul. Mascouche, Mascouche",
      year: "2024"
    }
  },
  {
    slug: "dkj-gascon-inc",
    title: "DKJ Gascon Inc.",
    titleEn: "DKJ Gascon Inc.",
    img: "/projets/DKJ Gascon Inc./IMG_0488.jpg",
    summary: "Aménagement paysager commercial pour entreprise avec espaces verts professionnels.",
    summaryEn: "Commercial landscaping for business with professional green spaces.",
    description: "Projet d'aménagement paysager commercial incluant la création d'espaces verts professionnels et l'intégration de végétation adaptée au milieu d'affaires.",
    descriptionEn: "Commercial landscaping project including the creation of professional green spaces and integration of vegetation adapted to the business environment.",
    gallery: [
      "/projets/DKJ Gascon Inc./IMG_0487.jpg",
      "/projets/DKJ Gascon Inc./IMG_0488.jpg",
      "/projets/DKJ Gascon Inc./IMG_0489.jpg",
      "/projets/DKJ Gascon Inc./IMG_0490.jpg",
      "/projets/DKJ Gascon Inc./IMG_0491.jpg",
      "/projets/DKJ Gascon Inc./IMG_3347.jpg",
      "/projets/DKJ Gascon Inc./IMG_3348.jpg",
      "/projets/DKJ Gascon Inc./IMG_6936.JPG",
      "/projets/DKJ Gascon Inc./IMG_6937.JPG",
      "/projets/DKJ Gascon Inc./IMG_6947.JPG",
      "/projets/DKJ Gascon Inc./IMG_6948.JPG",
      "/projets/DKJ Gascon Inc./IMG_6956.JPG",
      "/projets/DKJ Gascon Inc./IMG_6959.JPG",
      "/projets/DKJ Gascon Inc./IMG_6962.JPG",
      "/projets/DKJ Gascon Inc./IMG_6979.JPG"
    ],
    details: {
      budget: "Sur mesure",
      budgetEn: "Custom",
      duration: "6-8 semaines",
      durationEn: "6-8 weeks",
      materials: ["Végétation commerciale", "Pavé uni", "Éclairage paysager"],
      materialsEn: ["Commercial vegetation", "Interlocking pavers", "Landscape lighting"],
      location: "DKJ Gascon Inc.",
      locationEn: "DKJ Gascon Inc.",
      year: "2024"
    }
  },
  {
    slug: "plateau-de-la-gare",
    title: "Plateau de la Gare",
    titleEn: "Plateau de la Gare",
    img: "/projets/Plateau de la gare/IMG_0523.jpg",
    summary: "Aménagement paysager moderne pour un espace d'habitation chaleureux avec design contemporain.",
    summaryEn: "Modern landscaping for a warm residential space with contemporary design.",
    description: "Projet d'aménagement paysager complet incluant la conception d'espaces verts, l'installation de végétation adaptée au climat québécois, et la création d'un environnement harmonieux entre architecture et nature.",
    descriptionEn: "Complete landscaping project including the design of green spaces, installation of vegetation adapted to the Quebec climate, and creation of a harmonious environment between architecture and nature.",
    gallery: [
      "/projets/Plateau de la gare/IMG_0523.jpg",
      "/projets/Plateau de la gare/IMG_0524.jpg",
      "/projets/Plateau de la gare/IMG_0525.jpg",
      "/projets/Plateau de la gare/IMG_0526.jpg",
      "/projets/Plateau de la gare/IMG_3582 2.jpg",
      "/projets/Plateau de la gare/IMG_3582.jpg",
      "/projets/Plateau de la gare/IMG_8011.JPG",
      "/projets/Plateau de la gare/IMG_8012.JPG",
      "/projets/Plateau de la gare/IMG_8013.JPG",
      "/projets/Plateau de la gare/IMG_8014.JPG",
      "/projets/Plateau de la gare/IMG_8063.JPG"
    ],
    details: {
      budget: "Sur mesure",
      budgetEn: "Custom",
      duration: "8-10 semaines",
      durationEn: "8-10 weeks",
      materials: ["Végétation native", "Pavé uni", "Éclairage paysager", "Système d'irrigation"],
      materialsEn: ["Native vegetation", "Interlocking pavers", "Landscape lighting", "Irrigation system"],
      location: "Plateau de la Gare, Mirabel",
      locationEn: "Plateau de la Gare, Mirabel",
      year: "2024"
    }
  },
  {
    slug: "station-g",
    title: "Station G",
    titleEn: "Station G",
    img: "/projets/Station G/IMG_7248.JPG",
    summary: "Aménagement paysager commercial avec design moderne et fonctionnel.",
    summaryEn: "Commercial landscaping with modern and functional design.",
    description: "Projet commercial avec aménagement paysager moderne incluant la création d'espaces verts fonctionnels et l'intégration de végétation contemporaine.",
    descriptionEn: "Commercial project with modern landscaping including the creation of functional green spaces and integration of contemporary vegetation.",
    gallery: [
      "/projets/Station G/IMG_7248.JPG",
      "/projets/Station G/IMG_7249.JPG",
      "/projets/Station G/IMG_9453.jpg",
      "/projets/Station G/IMG_9468.jpg",
      "/projets/Station G/IMG_9470.jpg",
      "/projets/Station G/IMG_9471.jpg",
      "/projets/Station G/IMG_9472.jpg"
    ],
    details: {
      budget: "Sur mesure",
      budgetEn: "Custom",
      duration: "4-5 semaines",
      durationEn: "4-5 weeks",
      materials: ["Végétation commerciale", "Pavé uni", "Éclairage paysager"],
      materialsEn: ["Commercial vegetation", "Interlocking pavers", "Landscape lighting"],
      location: "Station G",
      locationEn: "Station G",
      year: "2024"
    }
  }
];
